/* tslint:disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    users: User;
    snippets: Snippet;
    categories: Category;
    articles: Article;
  };
  globals: {};
}
export interface User {
  id: string;
  roles?: ('admin' | 'user')[];
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string;
  resetPasswordExpiration?: string;
  salt?: string;
  hash?: string;
  loginAttempts?: number;
  lockUntil?: string;
  password?: string;
}
export interface Snippet {
  id: string;
  title: string;
  description: string;
  createdAt: string;
  updatedAt: string;
  category: string | Category;
  content: {
    [k: string]: unknown;
  }[];
  tags: ('front-end' | 'testing' | 'fundamentals' | 'database' | 'design-pattern' | 'architecture' | 'architecture')[];
}
export interface Category {
  id: string;
  title?: string;
  updatedAt: string;
  createdAt: string;
}
export interface Article {
  id: string;
  title?: string;
  type?: 'news';
  updatedAt: string;
  createdAt: string;
}
