version: '3'

services:

  payload:
    image: node:18-alpine
    ports:
      - "3002:3002"
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    working_dir: /home/node/app/
    command: sh -c "yarn install && yarn dev"
    depends_on:
      - mongo
    environment:
      MONGODB_URI: mongodb+srv://codetips-dev:NiwFVfTXRyRiIRIL@cluster0.pqfii.mongodb.net/codetips-dev
      PAYLOAD_SECRET: f714e58210538792978804a1
      PORT: 3002
      NODE_ENV: development
      RENDER_EXTERNAL_URL: https://codetips-cms.onrender.com
      HOSTNAME: http://localhost:3002
      FRONTEND_URL: http://localhost:3000

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db
    logging:
      driver: none

volumes:
  data:
  node_modules:
